name:               web-view
version:            0.2.0
synopsis:           Type-safe HTML and CSS with intuitive layouts and composable styles. Inspired by Tailwindcss and Elm-UI
homepage:           https://github.com/seanhess/web-view
license:            BSD-3-Clause
license-file:       LICENSE
author:             Sean Hess
maintainer:         seanhess@gmail.com
category:           Web

extra-source-files:
  - README.md
  - CHANGELOG.md

language: GHC2021

ghc-options:
  - -Wall
  - -fdefer-typed-holes

default-extensions:
  - OverloadedStrings
  - OverloadedRecordDot
  - DuplicateRecordFields
  - NoFieldSelectors

dependencies:
  - base >=4.16.4.0 && <5
  - containers >= 0.6 && <1
  - casing > 0.1.3.0 && <0.2
  - bytestring >= 0.10 && <0.13
  - effectful >= 2.0 && <3
  - string-interpolate >= 0.3 && <0.4
  - text >=1.2 && <3
  - file-embed >= 0.0.10 && <0.1

library:
  source-dirs: src

executables:
  example:
    main:                Main.hs
    source-dirs:         example
    dependencies:
    - http-types
    - http-api-data >= 0.6
    - web-view
    - wai >= 3.0
    - warp

tests:
  tests:
    main:                Tests.hs
    source-dirs:         test
