name:               web-view
version:            0.5.0
synopsis:           Type-safe HTML and CSS with intuitive layouts and composable styles.
homepage:           https://github.com/seanhess/web-view
github:             seanhess/web-view
license:            BSD-3-Clause
license-file:       LICENSE
author:             Sean Hess
maintainer:         seanhess@gmail.com
category:           Web
description:
  Type-safe HTML and CSS with intuitive layouts and composable styles. Inspired by Tailwindcss and Elm-UI
  .
  See documentation for the @Web.View@ module below

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - embed/preflight.css
  - test/resources/basic.txt
  - test/resources/escaping.txt
  - test/resources/nested.txt
  - test/resources/nocssattrs.txt
  - test/resources/nocss.txt
  - test/resources/raw.txt

language: GHC2021

ghc-options:
  - -Wall
  - -fdefer-typed-holes

default-extensions:
  - OverloadedStrings
  - OverloadedRecordDot
  - DuplicateRecordFields
  - NoFieldSelectors

dependencies:
  - base >=4.16 && <5
  - bytestring >= 0.11 && <0.13
  - containers >= 0.6 && <1
  - casing > 0.1.3.0 && <0.2
  - effectful-core >= 2.3 && <3
  - text >= 1.2 && <3
  - string-interpolate >= 0.3.2 && <0.4
  - file-embed >= 0.0.10 && <0.1
  - http-types >= 0.12 && <0.13
  - html-entities >= 1.1.4.7 && <1.2

library:
  source-dirs: src

tests:
  test:
    main:        Spec.hs
    source-dirs: test/
    build-tools: skeletest:skeletest-preprocessor
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -F -pgmF=skeletest-preprocessor
    dependencies:
      - web-view
      - Diff >= 0.5 && <1.0
      - skeletest
