name:               web-ui
version:            0.1.0
synopsis:           Typed HTML UIs with simplified layout, and ergonomic composition of styles. Inspired by Tailwindcss
homepage:           https://github.com/seanhess/web-ui
license:            BSD-3-Clause
license-file:       LICENSE
author:             Sean Hess
maintainer:         seanhess@gmail.com
category:           Web

extra-source-files:
  - README.md
  - CHANGELOG.md

language: GHC2021

ghc-options:
  - -Wall

default-extensions:
  - TypeFamilies
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - OverloadedRecordDot
  - OverloadedStrings
  - OverloadedLists
  - QuasiQuotes
  - DuplicateRecordFields
  - NoFieldSelectors

dependencies:
  - base >=4.16.4.0
  - text
  - containers
  - mtl

library:
  source-dirs: src

executables:
  example:
    main:                Example.hs
    source-dirs:         example
    dependencies:
    - web-ui
    - scotty

tests:
  tests:
    main:                Test.hs
    source-dirs:         test
