name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check packages
        run: |
          nix flake check
          # Build all devShells for the current system
          # FIXME figure out how to add this to: nix flake check
          # nix develop -c cabal test --dry-run
          # nix develop .#ghc982-web-view -c cabal test --dry-run
          # cd example
          # nix develop ..#ghc966-example -c cabal test --dry-run
          # nix develop ..#ghc982-example -c cabal test --dry-run
