name: Haskell CI

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write # for cachix

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - uses: cachix/cachix-action@v14
        with:
          name: hyperbole
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check packages
        run: |
          nix flake check

